const PlantsData=[
   {
       ScientificName : "Zamioculcas zamiifolia" ,
      PlantName: "Zuzu plant",
      FamilyName : "Araceae",
      PlantCost : "Rs.259",
      ReferenceLink : "https://en.wikipedia.org/wiki/Zamioculcas",
      Uses : "According to the studies by NASA, the ZZ plant is efficient in removing harmful contaminants such as formaldehyde, benzene, xylene, trichloroethylene, toluene and carbon dioxide from the air. ",
      Toxicity : "Zamioculcas zamiifolia is part of the family Araceae, which includes many poisonous genera, such as Philodendron and Monstera.",
      Caution : "Not pet friendly and do not allow kids to touch the plant.",
      WateringTips : "Water once in two weeks",
      NeedOfSunlight : "Need low sunlight, place it 5-6 feet away of sunlight place or place it in low light area",
      PlantImage : "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSfKG7WECCF-BF-H9POmXjfNSX3VitrP1yRcs-XR9Jeng&s",
      PlantFilter : ["Air Purifying Plants","Indoor Plants","Succulents"],
      Rating : 4
   },
   {
       ScientificName : "Adenium" ,
       PlantName : "Desert Rose",
       FamilyName : "Apocynaceae",
       PlantCost : "Rs.299",
       ReferenceLink : "https://en.wikipedia.org/wiki/Adenium",
       Uses : "Air Purification, Stress Relief and Low maintenance",
       Toxicity : "All parts of the plant are toxic.",
       Caution : "Not pet friendly and do not allow kids to touch the plant.",
       WateringTips : "Water 3-4 times in a week.",
       NeedOfSunlight : "Need 5-6 hours full sunlight, place it in sunlight place.",
       PlantImage : "https://hgtvhome.sndimg.com/content/dam/images/hgtv/products/2020/3/11/8/rx_amazon_two-desert-rose-bonsai-plants.jpeg.rend.hgtvcom.616.462.suffix/1583956224724.jpeg",
       PlantFilter : ["Succulents","Medicinal Plants","Outdoor Plants"],
       Rating : 4
    },
    {
       ScientificName : "Rose of Sharon" ,
       PlantName : "Hibiscus",
       PlantType : "Outdoor Plant",
       FamilyName : "Malvaceae",
       PlantCost : "Rs.299",
       ReferenceLink : "https://en.wikipedia.org/wiki/Hibiscus",
       Uses : "Hibiscus used for decorative and medicinal purposes to decrease blood pressure.",
       Toxicity : "Not at all poisnous to humans",
       Caution : "you should be careful when the climate is too hot. High temperatures and heat can increase the risk of sunburn and overheating, thus producing droopy leaves.",
       WateringTips : "For the first week after planting, water daily, tapering off to once every two days in the second week, and then about twice a week thereafter, when there is no rainfall.",
       NeedOfSunlight : "In general, the more sun this plant gets, the better. Hibiscus rosa-sinensis prefer full sun but will tolerate light shade.",
       PlantImage : "https://m.media-amazon.com/images/I/61qX+o5199L._AC_UF1000,1000_QL80_.jpg",
       PlantFilter : ["Flowering Plants","Medicinal Plants","Outdoor Plants","Pet Friendly Plants"],
       Rating : 5
    },
    {
       ScientificName : "Hydrangea" ,
       PlantName : "Hortensia",
       FamilyName : "Hydrangeaceae",
       PlantCost : "Rs.299",
       ReferenceLink : "https://en.wikipedia.org/wiki/Hydrangea",
       Uses : "People use hydrangea for bladder infections, prostate infections, enlarged prostate, kidney stones, and other conditions, but there is no good scientific evidence to support these uses.",
       Toxicity : "Not at all poisnous to humans",
       Caution : "Not pet friendly.",
       WateringTips : "watering when the first inch of soil feels dry to the touch.",
       NeedOfSunlight : "Ideally receiving sun in the morning hours and shade in the afternoon. Needs partial sunlight",
       PlantImage : "https://img.crocdn.co.uk/images/products2/pl/20/00/03/44/pl2000034434_card3_lg.jpg",
       PlantFilter : ["Flowering Plants","Outdoor Plants","Medicinal Plants"],
       Rating : 5
    },
    {
       ScientificName : "Prayer Plant" ,
       PlantName : "Maranta leuconeura",
       FamilyName : "Marantaceae",
       PlantCost : "Rs.320",
       ReferenceLink : "https://en.wikipedia.org/wiki/Maranta_leuconeura",
       Uses : "Plants will produce wax, some of which are harvested and used, like, Calathea lutea, grown to make waterproof baskets because of its durable, waxy leaves.",
       Toxicity : "Non-toxic to pets",
       Caution : "avoid waterlogging the soil and letting water sit on the leaves.",
       WateringTips : "Water every 1-2 weeks, allowing the soil to dry out half way down between waterings",
       NeedOfSunlight : "Prayer plants can tolerate low light conditions, they do best in bright, indirect light. They don't like direct sunlight. Prefer a place with high humidity.",
       PlantImage : "https://img.staticmb.com/mbcontent/images/uploads/2023/11/prayer-plant%20(1).jpg",
       PlantFilter : ["Indoor Plants","Air Purifying Plants","Pet Friendly Plants"],
       Rating : 4
    },
    {
       ScientificName : "Blue false indigo" ,
       PlantName : "Baptisia australis",
       FamilyName : "Fabaceae",
       PlantCost : "Rs.282",
       ReferenceLink : "https://en.wikipedia.org/wiki/Baptisia_australis",
       Uses : "Native Americans used False Indigo as an antiseptic, anti-catarrhal, febrifuge and stimulant purgative. They used it to stimulate immune responses to infection, treat ear, nose and throat problems.",
       Toxicity : "Low levels of toxicity",
       Caution : "This plant is listed as toxic. If ingested it can cause blurred vision, vomiting and vertigo.",
       WateringTips : "Keep a false indigo watered regularly for the first year, but after this, it will do well with about 1 inch of water every couple of weeks.",
       NeedOfSunlight : "Blue false indigo does best in full sun, although it can tolerate light shade.",
       PlantImage : "https://www.butterflyeffectfarm.com/wp-content/uploads/2023/03/blue-false-indigo-630x630.jpeg",
       PlantFilter : ["Outdoor Plants","Medicinal Plants","Flowering Plants"],
       Rating : 4
    },
    {
       ScientificName : "Thuja" ,
       PlantName : "Thuja plant",
       FamilyName : "Cupressaceae",
       PlantCost : "Rs.149",
       ReferenceLink : "https://en.wikipedia.org/wiki/Thuja",
       Uses : "They are widely grown as ornamental trees, and extensively used for hedges. A number of cultivars are grown and used in landscapes. Homeowners will sometimes plant them as privacy trees.",
       Toxicity : "Likely, safe when products are taken in correct amount. If, not taken in correct amount they are unsafe.",
       Caution : "Within the first two years from planting, Thuja cultivars will not have a fully developed root system that would allow it to support itself.",
       WateringTips : "Water a plant when the soil feels dry to touch.",
       NeedOfSunlight : "Need 5-6 hours full sunlight, place it in sunlight place.",
       PlantImage : "https://nurserylive.com/cdn/shop/products/nurserylive-arborvitae-plant.jpg?v=1634213586",
       PlantFilter : ["Indoor Plants","Medicinal Plants"],
       Rating : 4
    },
    {
     ScientificName : "Epipremnum aureum" ,
     PlantName : "Golden Pothos",
     FamilyName : "Araceae",
     PlantCost : "Rs.182",
     ReferenceLink : "https://en.wikipedia.org/wiki/Epipremnum_aureum",
     Uses : "Air Cleaner. NASA includes the Golden Pothos plant on a list of recommended plants for air purification. It removes benzene, formaldehyde, toluene, and xylene from the air. In fact, the NASA study saw that Golden Pothos was one of the best household plants for removing toxins!",
     Toxicity : "Toxic to pets and children",
     Caution : "This plant contains invisible needle-shaped crystals, which make the golden pothos toxic to cats, dogs and people, especially to young children and babies. So, it is best to keep the plant out of reach from your furry friends and kids.",
     WateringTips : "Water your Pothos every 1-2 weeks, allowing soil to dry out between waterings.",
     NeedOfSunlight : "Pothos plants thrive in bright, indirect light, but they can tolerate medium to low indirect light.",
     PlantImage : "https://nouveauraw.com/wp-content/uploads/2020/01/Pothos-Golden-Pothos-plant-800-great-coloring.png",
     PlantFilter : ["Indoor Plants","Outdoor Plants","Air Purifying Plants"],
     Rating : 5
  },
  {
     ScientificName : "Chlorophytum comosum" ,
     PlantName : "Spider plant",
     FamilyName : "Asparagaceae",
     PlantCost : "Rs.270",
     ReferenceLink : "https://en.wikipedia.org/wiki/Chlorophytum_comosum",
     Uses : "Studies have shown that spider plant is quite effective in cleaning indoor air by absorbing chemicals including formaldehyde, xylene, benzene, and carbon monoxide in homes or offices. Thick, fleshy roots allow spider plant to tolerate inconsistent watering.",
     Toxicity : "Non-toxic",
     Caution : "They do not tolerate low light conditions, so make sure not to place them indoors. If you notice that your spider plant's leaves are turning yellow or brown, it may be getting too much direct light or not enough light. To remedy this, adjust the placement of your plant to get the right amount of light it needs.",
     WateringTips : "Try to water your spider plant about once a week.",
     NeedOfSunlight : "A spider plant likes bright, indirect light. Avoid direct sunlight as it has the potential to scorch the leaves.",
     PlantImage : "https://nurtureplant.in/wp-content/uploads/2019/09/spider-plant.jpg",
     PlantFilter : ["Outdoor Plants","Indoor Plants","Pet Friendly Plants","Air Purifying Plants"],
     Rating : 5
  },
  {
     ScientificName : "Spathiphyllum" ,
     PlantName : "Peace Lily",
     FamilyName : "Araceae",
     PlantCost : "Rs.158",
     ReferenceLink : "https://en.wikipedia.org/wiki/Spathiphyllum",
     Uses : "Air Purification Properties, Natural Air Freshener, Non-Allergenic Flowers, Great for Boosting Mental Health, Improves Sleep Quality and A Low Maintenance Plant",
     Toxicity : "Mildly toxic to humans and other animals when ingested.",
     Caution : "Peace lilies are susceptible to root rot, so it's very important to make sure the plant has a chance to dry out between waterings and that the container it lives in drains well. Choose a container with drainage holes and place a saucer under to catch water that drains out.",
     WateringTips : "Whenever the top inch of soil is dry, water the plant until the overflow starts to come out of the bottom of the container.",
     NeedOfSunlight : "Peace lilies do very well in low-light situations, even flowering with as little as two to four hours of sunlight per day.",
     PlantImage : "https://m.media-amazon.com/images/I/41XTG8ZsUUL._AC_UF1000,1000_QL80_.jpg",
     PlantFilter : ["Indoor Plants","Air Purifying Plants","Flowering Plants"],
     Rating : 4
  },
  {
   ScientificName : "Aloe barbadensis miller" ,
   PlantName : "Aloe vera",
   FamilyName : "Asphodelaceae",
   PlantCost : "Rs.180",
   ReferenceLink : "https://en.wikipedia.org/wiki/Aloe_vera",
   Uses : "Aloe vera has been traditionally used to treat skin injuries (burns, cuts, insect bites, and eczemas) and digestive problems because its anti-inflammatory, antimicrobial, and wound healing properties.",
   Toxicity : "Aloe vera is not at all toxic.",
   Caution : "Place your aloe in a bright, sunny place. Otherwise, it will go dormant and stop growing.",
   WateringTips : "Water the plant heavily about once every two weeks, waiting until the soil dries out fully.",
   NeedOfSunlight : "To stay healthy, aloe plants need bright, indirect sunlight. Often, you can set the plant in your kitchen window, and it will get plenty of sunshine. If you're growing aloe vera outdoors, it should go in a sunny spot. Don't just move an indoor plant to full sun, though, as it can, ironically, get sunburn.",
   PlantImage : "https://m.media-amazon.com/images/I/61vzgIolFnS._AC_UF1000,1000_QL80_.jpg",
   PlantFilter : ["Indoor Plants","Outdoor Plants","Pet Friendly Plants","Succulents","Medicinal Plants"],
   Rating : 5
  },
  {
   ScientificName : "Nyctanthes arbor-tristis" ,
   PlantName : "Night-blooming jasmine",
   FamilyName : "Oleaceae",
   PlantCost : "Rs.299",
   ReferenceLink : "https://en.wikipedia.org/wiki/Nyctanthes_arbor-tristis",
   Uses : "From leaves to the roots, the whole Parijat plant is very useful for various healing properties. It is known to improve the function of insulin and reduce the symptoms of diabetes.",
   Toxicity : "toxic to mammals, including dogs and humans at high doses.",
   Caution : "Parijat leaves have a bitter and sharp taste that can cause vomiting for first time consumers. Continuous use of parijat leaves can cause gastric lesions as it contains methyl salicylate.",
   WateringTips : "Pour 4 cups (Approx. 250 ml) of water when the topsoil (1-2 inches) in the pot feels dry to touch",
   NeedOfSunlight : "At least 6 hours of sunlight or at least 6 hours of sunlight and natural light for the rest of the day.",
   PlantImage : "https://m.media-amazon.com/images/I/41tqu196+tL._AC_UF1000,1000_QL80_.jpg",
   PlantFilter : ["Outdoor Plants","Medicinal Plants"],
   Rating : 4
  },
  {
   ScientificName : "Strelitzia reginae" ,
   PlantName : "bird of paradise",
   FamilyName : "Strelitziaceae",
   PlantCost : "Rs.310",
   ReferenceLink : "https://en.wikipedia.org/wiki/Strelitzia_reginae",
   Uses : "The large leaves of the Bird of Paradise act as natural air purifiers and effectively remove toxins like formaldehyde and benzene from the air.",
   Toxicity : "minimally toxic to humans.",
   Caution : "🌺 Bird of Paradise is not toxic to humans, but ingestion can cause mild effects. 🐾 Keep the plant out of pets' reach as it can irritate them. 🧪 Scientific evidence of toxicity is scarce, debunking common misconceptions.",
   WateringTips : "Water every 1-2 weeks, allowing soil to dry out between waterings.",
   NeedOfSunlight : "Paradise plant at least 4-6 hours of bright light every day to ensure optimal growth.",
   PlantImage : "https://nurserylive.com/cdn/shop/products/nurserylive-plants-bird-of-paradise-plant-16968640528524.jpg?v=1634214531",
   PlantFilter : ["Indoor Plants","Air Purifying Plants","Flowering Plants"],
   Rating : 3
  },  
  {
   ScientificName : "Curio rowleyanus" ,
   PlantName : "String-of-Pearls",
   FamilyName : "Asteraceae",
   PlantCost : "Rs.170",
   ReferenceLink : "https://en.wikipedia.org/wiki/Curio_rowleyanus",
   Uses : "Indoor air quality gets a boost from the String of Pearls plant. it holds traditional medicinal uses, including antimicrobial and anticancer properties.",
   Toxicity : "minor toxic shoulld not be consumed by humans.",
   Caution : "string of pearls plant is toxic to dogs as well as humans. In humans, eating part of the plant can cause moderate gastrointestinal symptoms, such as nausea and vomiting.",
   WateringTips : "Don't water them too frequently, and allow the soil to completely dry out between each water. Once every two to three weeks is usually enough during spring and summer, and less during winter.",
   NeedOfSunlight : "They're best when kept in direct sunlight during the softer morning hours, then moved to a spot that gets diffused, indirect light, or partial shade during the harsher afternoon hours.",
   PlantImage : "https://i.etsystatic.com/24507111/r/il/df79b3/3360985744/il_1080xN.3360985744_kho8.jpg",
   PlantFilter : ["Indoor Plants","Outdoor Plants","Air Purifying Plants","Succulents"],
   Rating : 3
  },
  {
   ScientificName : "Nephrolepis exaltata" ,
   PlantName : "Sword fern",
   FamilyName : "Nephrolepidaceae",
   PlantCost : "Rs.460",
   ReferenceLink : "https://en.wikipedia.org/wiki/Nephrolepis_exaltata",
   Uses : "This evergreen plant not only helps to rid the home of harmful toxins it improves humidity by helping to restore moisture to the air naturally too. Because of these air-purifying properties, the Boston Fern is said to offer real health benefits to those who suffer from dry skin or irritably dry noses or throats.",
   Toxicity : "Toxic to humans",
   Caution : " If they are eaten, you will experience a painful burning sensation in your mouth.You may have difficulty swallowing and your voice may become horse.",
   WateringTips : "Watering your fern twice a week and misting it in between.",
   NeedOfSunlight : "Cool morning sun is ideal for Boston ferns. They need at least a couple of hours of bright, filtered or indirect light each day. Direct sun can burn them, but they won't grow in total shade either.",
   PlantImage : "https://5.imimg.com/data5/SELLER/Default/2022/9/CU/SW/BG/159591572/boston-fern-indoor-plant-500x500.jpg",
   PlantFilter : ["Indoor Plants","Air Purifying Plants"],
   Rating : 3
  },
  {
   ScientificName : "Philodendron hederaceum" ,
   PlantName : "Philodendron",
   FamilyName : "Araceae",
   PlantCost : "Rs.180",
   ReferenceLink : "https://en.wikipedia.org/wiki/Philodendron",
   Uses : "Philodendrons are thought to improve air quality in the home. Kings of foliage, philodendron's veiny, sprawling leaves are great to look at and even better at absorbing carbon dioxide and other toxins from the air! ",
   Toxicity : "Philodendrons produce a toxin called calcium oxalate which is toxic to humans if ingested.",
   Caution : "Simply touching the leaves is fine if you wash your hands immediately, but if you want to be doubly safe then always wear gloves when handling your Philodendron.",
   WateringTips : "Philodendron enjoys weekly watering sessions, allowing its soil to completely dry out between waterings to prevent overwatering and root rot. During the winter months feel free to water your Philodendron less frequently, adjusting to let it dry out fully.",
   NeedOfSunlight : "Philodendrons tolerate low light levels, but they do grow faster in bright, indirect sunlight. You must avoid placing your philodendron in direct sunlight because this could burn the leaves quickly.",
   PlantImage : "https://rukminim2.flixcart.com/image/850/1000/l3lx8cw0/plant-sapling/s/i/s/no-perennial-yes-philodendron-plant-p5-1-elite-green-original-imagep2zyashtgaz.jpeg?q=90&crop=false",
   PlantFilter : ["Indoor Plants","Air Purifying Plants","Flowering Plants"],
   Rating : 4
  },
  {
   ScientificName : "Crassula ovata" ,
   PlantName : "Jade plant",
   FamilyName : "Crassulaceae",
   PlantCost : "Rs.160",
   ReferenceLink : "https://en.wikipedia.org/wiki/Crassula_ovata",
   Uses : "In some regions, the jade plant is used to treat wounds. Moreover, the jade plant can help deal with issues such as indigestion and diarrhoea.",
   Toxicity : "The toxins in the jade plant that are poisonous are still unknown but are capable of causing gastric distress, heartbeat irregularities, and depression. Most cases of poisoning are mild but in rare cases, the ingestion of the jade plant has caused more serious effects such as convulsions.",
   Caution : "Jade plants don't like being too wet. Be sure your planter has drainage holes, and you're emptying excess water from the saucer.",
   WateringTips : "let the top 1 to 2 inches of soil dry out between waterings.",
   NeedOfSunlight : "Jade plants need at least 4 hours of direct sunlight each day. Young plants should be kept in bright, indirect sunlight.",
   PlantImage : "https://www.rollingnature.com/cdn/shop/products/PLJDCEJRGL-W-Part1.jpg?v=1669452813&width=1946",
   PlantFilter : ["Indoor Plants","Air Purifying Plants","Flowering Plants","Succulents"],
   Rating : 3
  },
  {
   ScientificName : "Hedera helix" ,
   PlantName : "English ivy",
   FamilyName : "Araliaceae",
   PlantCost : "Rs.100",
   ReferenceLink : "https://en.wikipedia.org/wiki/Hedera_helix",
   Uses : "English ivy is an evergreen plant that offers some surprising benefits. As a houseplant, it may help to purify the air. When ingested, some research suggests that it may provide antioxidant and anti-inflammatory benefits. In addition, it appears to be useful in reducing cough related to colds and viral infections.",
   Toxicity : "Ingestion may cause minor symptoms such as rash, vomiting or diarrhea.",
   Caution : "English ivy has medium water needs, so it doesn't want to dry out completely, but it also can't stay wet for extended periods, or the roots will rot and die.",
   WateringTips : "Ivies don't like wet soil. Wait to water until the top inch or so of the potting mix dries out.",
   NeedOfSunlight : "English ivy can also be used as ground cover in dry shade.",
   PlantImage : "https://cdn.shopify.com/s/files/1/0598/1444/5195/files/image_y9p.webp?v=1710859897",
   PlantFilter : ["Indoor Plants","Air Purifying Plants"],
   Rating : 3
  },
  {
   ScientificName : "Impatiens walleriana" ,
   PlantName : "Impatiens",
   FamilyName : "Balsaminaceae",
   PlantCost : "Rs.500",
   ReferenceLink : "https://en.wikipedia.org/wiki/Impatiens",
   Uses : "Different parts of the plant are used as traditional remedies for disease and skin afflictions. Juice from the leaves is used to treat warts and snakebite, and the flower is applied to burns.",
   Toxicity : "Not toxic",
   Caution : "While Impatiens are not poisonous, eating any part of the plant can cause an adverse reaction, so it is best to take care when including this plant in your landscape or living space. If possible, try to feature Impatiens in areas not accessible to kids or pets.",
   WateringTips : "Impatiens are not drought tolerant, so they need to be watered regularly during dry spells to keep the soil consistently moist and prevent the plants from wilting.",
   NeedOfSunlight : "Impatiens perform best in moist, well-drained soils in partial shade. Sites that receive 2 to 4 hours of filtered sun during the day or morning sun and afternoon shade are usually ideal.",
   PlantImage : "https://organicbazar.net/cdn/shop/files/Impatiens_2.jpg?v=1707302546",
   PlantFilter : ["Outdoor Plants","Flowering Plants","Medicinal Plants"],
   Rating : 4
  },
  {
   ScientificName : "Begonia" ,
   PlantName : "Begonia",
   FamilyName : "Begoniaceae",
   PlantCost : "Rs.150",
   ReferenceLink : "https://en.wikipedia.org/wiki/Begonia",
   Uses : "Extracts from begonias have been used to treat respiratory infections and skin diseases.However, always remember to consult a healthcare professional before using plants for medicinal purposes.",
   Toxicity : "Not toxic",
   Caution : "Although begonias prefer well-drained soil, underwatering is still an issue that can cause foliage to dry out and brown. ",
   WateringTips : "water every two to four days. When it's hot and dry you'll need to water more often than when the air cools down and the soil holds more moisture.",
   NeedOfSunlight : "Begonias are tolerant of a range of light conditions, from full sun to shade. In colder climates, plants can tolerate more light. In warm regions, they need protection from hot afternoon sun to prevent leaf scald.",
   PlantImage : "https://nurserylive.com/cdn/shop/products/nurserylive-hardy-begonia-plant.jpg?v=1634223205",
   PlantFilter : ["Outdoor Plants","Flowering Plants","Medicinal Plants","Air Purifying Plants"],
   Rating : 4
  }

   ]

module.exports= PlantsData;

